### ISSUE TITLE
Error running the demo locally

### ISSUE THREAD

**Issue by andreloureiro** [Widdershin/cycle-remote-data#1]
Hey @Widdershin! Thanks for this driver, awesome approach to handle remote stuff :)

I've got an error trying to run the demo gist locally.

## How to reproduce
- Type "cycle" in the input field
- When the result comes in, delete all the text in the input, you'll get:
```javascript
Uncaught TypeError: (intermediate value)(intermediate value)._add is not a function
```

Seems like `NotAsked` isn't a stream. In this part, switching from `NotAsked` to `xs.empty()` solves the issue:
```javascript
query === ''
  ? NotAsked
  : sources.RemoteData.request({
      url: `https://api.github.com/search/repositories?q=${query}`,
      method: 'GET'
    })
```

**Comment by andreloureiro** [comment]
Oh dumb me :man_facepalming:. If `xs.empty()` works, than `xs.of(NotAsked)` works as well and brings the desired behaviour! I'll submit a PR when possible to add this change to the gist. Thanks again @Widdershin :)

**Comment by Widdershin** [comment]
More like dumb me! Thanks for noticing and making a pull request 😄
